// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTzUx6JifZnc4PunZ6lin75brG_pUctnE',
    appId: '1:269728125034:web:296d17f27611a99d43ba13',
    messagingSenderId: '269728125034',
    projectId: 'fp-mood-diary',
    authDomain: 'fp-mood-diary.firebaseapp.com',
    storageBucket: 'fp-mood-diary.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSABXhjB62UDMYpirxjrcvY06OliEDQgI',
    appId: '1:269728125034:android:26724efcea14dfb143ba13',
    messagingSenderId: '269728125034',
    projectId: 'fp-mood-diary',
    storageBucket: 'fp-mood-diary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0wrv0LiOB2RhuT0Wq2CKIjwBOfdORpWQ',
    appId: '1:269728125034:ios:2aa3b45974d3aaad43ba13',
    messagingSenderId: '269728125034',
    projectId: 'fp-mood-diary',
    storageBucket: 'fp-mood-diary.firebasestorage.app',
    iosBundleId: 'com.example.moodDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0wrv0LiOB2RhuT0Wq2CKIjwBOfdORpWQ',
    appId: '1:269728125034:ios:2aa3b45974d3aaad43ba13',
    messagingSenderId: '269728125034',
    projectId: 'fp-mood-diary',
    storageBucket: 'fp-mood-diary.firebasestorage.app',
    iosBundleId: 'com.example.moodDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTzUx6JifZnc4PunZ6lin75brG_pUctnE',
    appId: '1:269728125034:web:9cbea69b913a67c043ba13',
    messagingSenderId: '269728125034',
    projectId: 'fp-mood-diary',
    authDomain: 'fp-mood-diary.firebaseapp.com',
    storageBucket: 'fp-mood-diary.firebasestorage.app',
  );
}
